# emumadz
package:
  name: emumadz
  version: "0.2.0"

source:
  path: .

build:
  number: 0
  noarch: python
  entry_points:
    - emumadz = parse_vcf:main

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - bcftools =1.19
    - gatk4 =4.5.0.0
    - pandas =2.0.0
    - pysam >=0.16.0
    - samtools =1.19.2
    - snpeff =5.2
    - ensembl-vep =114.2
    - perl >=5.32.1
    - perl-dbi >=1.643
    - perl-archive-zip >=1.6.8
    - perl-dbd-mysql >=4.050
    - perl-set-intervaltree >=0.12
    - perl-json >=4.10
    - perl-perlio-gzip >=0.20
    - perl-bio-bigfile >=1.07
    - perl-list-moreutils >=0.430    

test:
  imports:
    - parse_vcf
  commands:
    - parse_vcf --help

about:
  home: https://github.com/hoganlab-fish/whole_genome_sequencing
  license: MIT
  license_file: LICENSE
  summary: Enhanced MUtation MApping and Detection in Zebrafish
  description: |
    A conda package for SNP detection.
  dev_url: https://github.com/hoganlab-fish/whole_genome_sequencing

extra:
  recipe-maintainers:
    - tyronechen